site_name: Zleed Docs

repo_url: https://github.com/ZleedApp/ZleedDocs
repo_name: ZleedApp/ZleedDocs

copyright: Copyright &copy; 2022 Zleed

theme:
  name: material
  favicon: assets/favicon.ico
  font:
    text: Noto Sans
    code: Noto Sans Mono
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/x5AaXr5F
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ZleedApp
    - icon: fontawesome/brands/github
      link: https://github.com/ZleedApp

nav:
  - Home: /
  - About:
      - Contributing &amp; Support: about/contributing.md
      - Changelog: about/changelog.md
      - License: about/license.md
  - API:
      - Auth: api/auth.md
      - User: api/user.md

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true

extra_css:
  - css/custom.css